global using Microsoft.EntityFrameworkCore;
global using Persistence.Data;
global using ProductAPI.Extensions;
global using System.Net;
global using Application.Kafka.Messages;
global using Application.Interfaces;
global using Microsoft.AspNetCore.Mvc;
global using KafkaConsumer;
global using ProductProcessingService;
